"""PDF report generation using fpdf2."""
import io
import os
from datetime import datetime

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False


BLUE  = (24,  119, 242)
GREEN = (46,  125, 50)
RED   = (198, 40,  40)
DARK  = (28,  30,  33)
GRAY  = (96,  103, 112)
LIGHT = (240, 242, 245)


class MetaAdsPDF(FPDF):
    def __init__(self, brand_name="Meta Ads", brand_color=None):
        super().__init__()
        self.brand_name  = brand_name
        self.brand_color = brand_color or BLUE
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        r, g, b = self.brand_color
        self.set_fill_color(r, g, b)
        self.rect(0, 0, 210, 16, "F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 4)
        self.cell(0, 8, f"{self.brand_name} - Performance Report", ln=False)
        self.set_xy(0, 4)
        date_str = datetime.now().strftime("%d %b %Y")
        self.cell(200, 8, date_str, align="R")
        self.ln(14)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*GRAY)
        self.cell(0, 8, f"Page {self.page_no()} | Generated by Meta Ads Automation", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*self.brand_color)
        self.set_fill_color(*LIGHT)
        self.cell(0, 9, f"  {title}", ln=True, fill=True)
        self.ln(2)
        self.set_text_color(*DARK)

    def kpi_row(self, kpis: list):
        """kpis = list of (label, value) tuples, max 4"""
        w = 190 / len(kpis)
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(233, 235, 238)
        for label, value in kpis:
            x, y = self.get_x(), self.get_y()
            self.rect(x, y, w - 4, 18, "D")
            self.set_font("Helvetica", "", 7)
            self.set_text_color(*GRAY)
            self.set_xy(x + 3, y + 2)
            self.cell(w - 10, 4, label.upper())
            self.set_font("Helvetica", "B", 13)
            self.set_text_color(*DARK)
            self.set_xy(x + 3, y + 7)
            self.cell(w - 10, 8, str(value))
            self.set_xy(x + w, y)
        self.ln(22)

    def data_table(self, headers: list, rows: list, col_widths: list = None):
        if not rows:
            self.set_font("Helvetica", "I", 9)
            self.set_text_color(*GRAY)
            self.cell(0, 8, "No data available.", ln=True)
            return

        n = len(headers)
        total_w = 190
        if col_widths is None:
            col_widths = [total_w / n] * n

        # Header row
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*self.brand_color)
        self.set_text_color(255, 255, 255)
        self.set_draw_color(255, 255, 255)
        for h, w in zip(headers, col_widths):
            self.cell(w, 7, str(h)[:20], border=0, fill=True)
        self.ln()

        # Data rows
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*DARK)
        self.set_draw_color(233, 235, 238)
        for i, row in enumerate(rows):
            if self.get_y() > 270:
                self.add_page()
            fill = i % 2 == 0
            self.set_fill_color(248, 249, 250) if fill else self.set_fill_color(255, 255, 255)
            for val, w in zip(row, col_widths):
                self.cell(w, 6, str(val)[:22], border="B", fill=fill)
            self.ln()
        self.ln(4)


def generate_report(totals: dict, perf_df, time_df,
                    brand_name="Meta Ads", brand_color=None) -> bytes:
    if not FPDF_AVAILABLE:
        raise ImportError("fpdf2 not installed. Run: pip install fpdf2")

    color = brand_color or BLUE
    pdf   = MetaAdsPDF(brand_name=brand_name, brand_color=color)
    pdf.add_page()

    # ── Cover KPIs ───────────────────────────────────────────
    pdf.section_title("Account Summary")
    spend  = totals.get("total_spend", 0)
    clicks = totals.get("total_clicks", 0)
    leads  = totals.get("total_leads", 0)
    ctr    = totals.get("avg_ctr", 0)
    pdf.kpi_row([
        ("Total Spend",  f"Rs {spend:,.0f}"),
        ("Total Clicks", f"{clicks:,}"),
        ("Total Leads",  f"{leads:,}"),
        ("Avg CTR",      f"{ctr:.2f}%"),
    ])

    # ── Campaign Table ────────────────────────────────────────
    pdf.section_title("Campaign Performance")
    if not perf_df.empty:
        headers = ["Name", "Status", "Spend", "ROAS", "CTR", "Leads"]
        rows = []
        for _, r in perf_df.iterrows():
            rows.append([
                str(r["name"])[:24],
                str(r["status"]),
                f"Rs {r['total_spend']:,.0f}",
                f"{r['avg_roas']:.2f}",
                f"{r['avg_ctr']:.2f}%",
                str(int(r.get("leads", 0))),
            ])
        pdf.data_table(headers, rows, [60, 22, 28, 22, 22, 22])

    # ── Daily Breakdown ───────────────────────────────────────
    if not time_df.empty:
        pdf.add_page()
        pdf.section_title("Daily Performance Breakdown")
        headers = ["Date", "Spend", "Clicks", "Impressions", "ROAS", "CTR"]
        rows = []
        for _, r in time_df.tail(30).iterrows():
            rows.append([
                str(r.get("date",""))[:10],
                f"Rs {float(r.get('spend',0)):,.0f}",
                f"{int(r.get('clicks',0)):,}",
                f"{int(r.get('impressions',0)):,}",
                f"{float(r.get('roas',0)):.2f}",
                f"{float(r.get('ctr',0)):.2f}%",
            ])
        pdf.data_table(headers, rows, [30, 32, 28, 38, 30, 28])

    # ── Footer note ───────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GRAY)
    pdf.ln(4)
    pdf.cell(0, 5, f"Report generated: {datetime.now().strftime('%d %b %Y %H:%M')} | {brand_name} Reporting Portal", ln=True)

    return bytes(pdf.output())
